### PR TITLE
feat: Add Luhn (closes #120)

### LINKED ISSUE #120: Add Luhn practice exercise
Port the [luhn](https://github.com/exercism/problem-specifications/tree/main/exercises/luhn) exercise to V.

### PR DESCRIPTION
**Pull request by keiravillekode**

### CODE REVIEW

**Comment by keiravillekode** [comment]
https://github.com/exercism/vlang/pull/122 fixes the failure, which is not related to this PR.

**Comment by 1ethanhansen** [comment]
Would you mind updating this branch with the latest code from #122? Just to get that sweet sweet green color before merging :smile:

**Comment by keiravillekode** [comment]
Updated.

**Review by 1ethanhansen — APPROVED** [review]
LGTM

**Pull request merged**
