### PR TITLE
feat: set the track to active

### PR DESCRIPTION
**Pull request by 1ethanhansen**
@ErikSchierboom @iHiD now that there is a [track icon for V](https://github.com/exercism/website-icons/pull/144) I believe the track is ready to be set active!! I'll be working on the test runner in the background but my understanding is that's not required to launch a track, correct?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I've checked the repo, and it looks like the shared help.md/tests.md files are missing: https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-add-exercise-docs

As for the test runner: yes, you can launch without, but all of our recently released tracks have launched with a test runner as it makes it so much easier for the students to get started. I see that the test runner repo is already there: https://github.com/exercism/vlang-test-runner/ I'm happy for you to launch, but you'd have to be conscious of the fact that many students would expect the track to work via the online editor which would not be the case. I'm also happy to help whip up a simple v1 test runner for vlang, it shouldn't be that hard. Let me know what you think.

**Comment by 1ethanhansen** [comment]
oh yep you're right - not sure how I missed that. my bad! will add those and re-request review

**Comment by 1ethanhansen** [comment]
@ErikSchierboom I would much appreciate help on basic v1 test runner. I have minimal experience with Docker so I might be a bit out of my depth on that

**Comment by ErikSchierboom** [comment]
@1ethanhansen I'll try and whjp up something tomorrow.

**Comment by 1ethanhansen** [comment]
added missing docs in https://github.com/exercism/vlang/pull/47 @ErikSchierboom

**Review by ErikSchierboom — APPROVED** [review]
Approving pending #47 is merged first.

Just tested the online editor, and it works:

image

**Comment by ErikSchierboom** [comment]
HzJdFDZ

**Pull request merged**
